# IDE-specific agent configurations
# This file defines agent-specific settings for different IDEs

# Roo Code file permissions
# Each agent can have restricted file access based on regex patterns
# If an agent is not listed here, it gets full edit access
roo-permissions:
  # Core agents
  sead-analyst:
    fileRegex: "\\.(md|txt)$"
    description: "Documentation and text files"
  sead-project-manager:
    fileRegex: "\\.(md|txt)$"
    description: "Product documentation"
  sead-architect:
    fileRegex: "\\.(md|txt|yml|yaml|json)$"
    description: "Architecture docs and configs"
  sead-qa:
    fileRegex: "\\.(test|spec)\\.(js|ts|jsx|tsx)$|\\.md$"
    description: "Test files and documentation"
  sead-ux-expert:
    fileRegex: "\\.(md|css|scss|html|jsx|tsx)$"
    description: "Design-related files"
  sead-product-owner:
    fileRegex: "\\.(md|txt)$"
    description: "Story and requirement docs"
  sead-scrum-master:
    fileRegex: "\\.(md|txt)$"
    description: "Process and planning docs"
  sead-catalog-architect:
    fileRegex: "\\.(md|txt|json|yaml|yml)$"
    description: "Catalog and pattern documents"
  sead-pattern-extraction:
    fileRegex: "\\.(md|txt|json|yaml|yml)$"
    description: "Pattern extraction and analysis docs"

# Cline agent ordering
# Lower numbers appear first in the list
# Agents not listed get order 99
cline-order:
  # Core agents
  sead-master: 1
  sead-orchestrator: 2
  sead-project-manager: 3
  sead-analyst: 4
  sead-architect: 5
  sead-product-owner: 6
  sead-scrum-master: 7
  sead-developer: 8
  sead-qa: 9
  sead-ux-expert: 10
  sead-catalog-architect: 11
  sead-pattern-extraction: 12